spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    #redis数据库索引，默认是0
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dk.entity
  configuration:
    #    开启驼峰规则 (数据库)Table(create_time) -> (实体类)Entity(createTime)。不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true
    # 使用jdbc的getGeneratedKeys 可以获取数据库自增主键值
    use-generated-keys: true

# 打印sql
logging:
  level:
    cn.tycoding.mapper: DEBUG

pageRequest:
  pagesize: 4